set_property SRC_FILE_INFO {cfile:C:/FPGA/Assignment_1/FPGA/PongDesign/PongDesign.srcs/constrs_1/new/ponger.xdc rfile:../../../PongDesign.srcs/constrs_1/new/ponger.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports d_out_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports led_out_0]
