set_property SRC_FILE_INFO {cfile:C:/FPGA/Hcsr04/ultrasound.xdc rfile:../../../ultrasound.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports sonar_echo_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports sonar_trig_0]
