webtalk_init -webtalk_dir C:\\FPGA\\ImpedancePmod\\ImpedancePmod.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-01-07 21:15:50" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cm42rgka130uauc5aq1p5lpjc3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.842 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1578422088001" -context "sdk\\\\bsp/1578422088001"
webtalk_add_data -client sdk -key hwid -value "1573726299009" -context "sdk\\\\bsp/1578422088001"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1578422088001"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1578422088001"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1578422088001"
webtalk_add_data -client sdk -key uid -value "1578422091485" -context "sdk\\\\application/1578422091485"
webtalk_add_data -client sdk -key hwid -value "1573726299009" -context "sdk\\\\application/1578422091485"
webtalk_add_data -client sdk -key bspid -value "1578422088001" -context "sdk\\\\application/1578422091485"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1578422091485"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1578422091485"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1578422091485"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1578422091485"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1578422091485"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1578422091485"
webtalk_add_data -client sdk -key projSize -value "282.76953125" -context "sdk\\\\application/1578422091485"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1578428150099"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1578428150099"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1578428150099"
webtalk_add_data -client sdk -key DebugCount -value "34" -context "sdk\\\\bsp/1578428150099"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1578428150099"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1578428150099"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1578428150099"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1578428150099"
webtalk_transmit -clientid 4252146052 -regid "" -xml C:\\FPGA\\ImpedancePmod\\ImpedancePmod.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\FPGA\\ImpedancePmod\\ImpedancePmod.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\FPGA\\ImpedancePmod\\ImpedancePmod.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
